# Generated by Django 5.1.3 on 2024-11-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='aspects_covered',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.difficultyaspect'),
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='activities.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='difficultyaspect',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='activities.method'),
        ),
        migrations.CreateModel(
            name='StudentDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.difficultyaspect')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.chapter')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.method')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='activities.student')),
            ],
        ),
    ]
