# Generated by Django 5.1.3 on 2024-11-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_studentdifficulty_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdifficulty',
            name='method',
            field=models.ForeignKey(default='reduction to the same', on_delete=django.db.models.deletion.CASCADE, to='activities.method'),
            preserve_default=False,
        ),
    ]
