# Generated by Django 5.1.3 on 2024-11-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_studentdifficulty_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdifficulty',
            name='method',
        ),
    ]
